- app/data/mosques.ts
- app/layout.tsx
- app/page.tsx
- app/types/index.d.ts
- app/types/index.ts
- components/ui/mosque-card.tsx
- components/ui/tooltip.tsx
- package.json
- pnpm-lock.yaml
- 🐞 fix: fixes hydration error by moving `<Toaster />` component inside body tag
- ♻️ refactor: makes types declaration to be global
- 💄 style: remove hover scale effect on card to emphasize buttons inside them
- 👨🏿‍🦽 feat: add feature to download QR image
> :wheelchair: improve accessebbiilllityy

- biome.json
- components/sections/filters.tsx
- components/ui/institution-card.tsx
- components/ui/qrCodeDisplay.tsx
- package.json
- pnpm-lock.yaml
> :wheelchair: download generated qr image instead of raw image

- components/ui/header.tsx
> fix: eyesore header

- components/ui/institution-card.tsx
- Resolve hover UI untuk button `copy` dan `download`
- Tukar text ke BM
- Add more tooltips for better UX
> 🎨 Improve card component

- components/ui/institution-card.tsx
Buat PR baru sebab tak boleh commit dekat #35 (dah merged and closed)
Thank youu
> 🌐 Change text to BM

- app/data/institutions.ts
Adding data : 
- Masjid Ahmadi 
- Masjid An-Nur 
Adding coordinate for : 
- Masjid Setia Alam
> add: data masjid and add coord masjid setia alam

- app/data/institutions.ts
adding masjid jamek al-manar qr code
done tolong sikit
> adding masjid jamek al-manar qr code

- components/ui/institution-card.tsx
> :bug: fix copy button

- components/ui/institution-card.tsx
> 💄 style: fix ui in popup qr code

- app/rawak/page.tsx
> :bug: fix rawak image not loaded on first render

- app/data/institutions.ts
things some typos 
- change Mchondong to pulai chondong 
- change city "Kuala Lumpur" to "Segambut"
> fix: rename at Taqwa and city firdaus

- components/ui/institution-card.tsx
Update `capitalizeWords`. Fixed naming for following scenarios:
Institutions
- **Masjid Tok Keling (an-Nur) → Masjid Tok Keling (An-Nur)**
- **Jk Pbn Masjid Baru Kuala Ketil → JK PBN Masjid Baru Kuala Ketil**
- **Masjid Utm Kl → Masjid UTM KL**
- **Iium Gombak Mosque → IIUM Gombak Mosque**
- **Masjid Tengku Ampuan Afzan, Bandar Satelit (Mtaabsms) →  Masjid Tengku Ampuan Afzan, Bandar Satelit (MTAABSMS)**
- **Masjid Tengku Ampuan Afzan, Indera Mahkota (Mastaaf) → Masjid Tengku Ampuan Afzan, Indera Mahkota (MASTAAF)**
- and related
District
- **Kuala Lumpur, W.p. Kuala Lumpur → Kuala Lumpur, W.P. Kuala Lumpur**
> ✨ Optimize capitalizeWords function

- components/sections/filters.tsx
> 🐛 Update filter

- app/globals.css
> ✨Dark leaflet

- components/states-dropdown.tsx
- package.json
Add ability to reset dropdown value to default (Semua Negeri) by clicking `X`
> ✨Reset dropdown value

- app/page.tsx
before
https://github.com/user-attachments/assets/c5c79e85-5e2e-4766-b0ae-772fee0cd5d2
after
https://github.com/user-attachments/assets/303358f7-5f47-4509-8660-2c29378a3079
> 🐛 Fixed display issues for loading

- app/rawak/page.tsx
- components/sections/filters.tsx
> :bug: baiki pepijat

- app/rawak/page.tsx
> 🐛 Fix 'Cari di peta' button at page rawak

- app/page.tsx
Maaf #82 introduced a flicker bug bila less than 15 data loaded.
Removed unnecessary one line of code, setter
> 🐛 Fix flicker 

- app/page.tsx
Randomize the cards sorting everytime the page is reloaded/opened. This will helps other institutions to get a chance to be on top instead of seeing the same QR at the top everytime
> :sparkles: randomize card every reload

- app/rawak/page.tsx
due to on mobile view, a bit hard to tap on the lain-lain filter.
> :joy: add padding bottom to rawak page

- app/data/institutions.ts
- app/types/institutions.ts
- components/ui/institution-card.tsx
> - add desc (optional)

- app/data/institutions.ts
> 🧹 cleanup some more institution data

- app/[institution]/[id]/page.tsx
- app/types/institutions.ts
- components/custom-map.tsx
- components/map.tsx
- components/ui/category-label.tsx
- components/ui/institution-card.tsx
- components/ui/pageSection.tsx
Misc:
1. Fix some console errors
2. `others` category color to purple - trying to match available marker color
3. `Popup` to `Tooltip` -  better UX I think
4. 404 for nonexistent institution - instead of blank institution page
Future:
1. Marker with mosque/surau icon
2. Nice looking 404 page. Maybe something like random Quran verses
> ✨ Add marker color

- app/data/institutions.ts
Masjid Taman Impian Emas was at Cambodia (11.5539955398923895, 103.67005417671798)  🤭
> 🗃️ Update data

- app/data/institutions.ts
small cleanup for institutions
> small cleanup on institutions

- app/data/institutions.ts
Add Masjid Tok Lebai Hashim, Bukit Mertajam, Pulau Pinang.
> Update institutions.ts - Add Masjid Tok Lebai Hashim, Bukit Mertajam, Pulau Pinang.

- app/page.tsx
- components/sections/filters.tsx
Related #110 
**Before:**
https://github.com/user-attachments/assets/586b0152-813c-4bac-ad1f-02415a2fd1b2
**After:**
https://github.com/user-attachments/assets/69cedb80-8a05-4a5f-803f-60b6b336eff7
**Changes:**
- Fix institution category filtering
- Add institutions data prop to Filters component to ensure count display is correct
- Fix eslint error
- Combine search input into filters.tsx
> 🐛 Fix filtering not working properly

- app/layout.tsx
- app/page.tsx
- components/rawak-footer.tsx
> 💄 Show "Sedekah Rawak" button only at main page

- app/data/institutions.ts
Add Masjid Sungai Abong and Surau An Nur Presint 11
> Add institution for Masjid Sungai Abong and Surau An Nur Presint 11

- app/rawak/page.tsx
- Add "bg-background transition-colors duration-200 ease-in-out " to `PageSection` classnames
- This will fix : https://github.com/khrnchn/sedekah-je/issues/127
> Fix minor UI bug in `/rawak` page

- app/data/institutions.ts
added coordinates to some places and cleanup some more institutions data
> added coordinates and cleanup some more institutions data

- components/sections/filters.tsx
- components/states-dropdown.tsx
- components/ui/mode-toggle.tsx
Fixed the warnings at console
```
Warning: forwardRef render functions accept exactly two parameters: props and ref. Did you forget to use the ref parameter?
Warning: forwardRef render functions accept exactly two parameters: props and ref. Did you forget to use the ref parameter?
Warning: forwardRef render functions accept exactly two parameters: props and ref. Did you forget to use the ref parameter?
at header
at O (webpack-internal:///(ssr)/./node_modules/next-themes/dist/index.mjs:22:24)
at z (webpack-internal:///(ssr)/./node_modules/next-themes/dist/index.mjs:17:48)
at ThemeProvider (webpack-internal:///(ssr)/./components/theme-provider.tsx:13:26)
at Lazy
at body
at html
at RedirectErrorBoundary (webpack-internal:///(ssr)/./node_modules/next/dist/client/components/redirect-boundary.js …
```
> 🚨 Resolve forwardRef warning

- app/data/institutions.ts
smol add for coords for masjid and surau and fixing some incorrect location
> add more coords for masjid and surau

- components/ui/header.tsx
- adjusted tailwind colouring to ease read on dark mode
- modified description
`Senarai QR masjid, surau, dan institusi.` seems nicer to read compared to  `Senarai QR Masjid, Surau, Institusi`
> refactor: improve readability on dark mode, adjust text

- app/data/institutions.ts
- app/layout.tsx
- app/page.tsx
- app/rawak/page.tsx
- components/custom-map.tsx
- components/rawak-footer.tsx
1. add scroll to card when clicking on jana qr
2. remove ribbon
3. add a button for public to contribute qr
4. thanks claude
> :mag: add toggle for displaying map

- components/rawak-footer.tsx
todo : 
- change button color following dark mode like button sedekah rawak and muat naik qr
- #135 
areas changes : 
- footer file only classname
> Feat : improve the Ui button for footer button 

- app/data/institutions.ts
- Masjid Al Ittihad Kg Kumpulan Langkawi
> Add mosque

- app/data/institutions.ts
a) Masjid Ar Rabbani Melaka
b) Masjid Jamek Kemunting Perak
> Add two new mosque.

- app/data/institutions.ts
- Add boost QR for Masjid Saidina Umar Al-Khattab, Bukit Damansara. [Source](https://msua.com.my/msua)
- Update state
> Update data institutions

- components/share.tsx
- components/ui/icons.tsx
Old&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;New
> fix: improve X icon visibility in dark mode

- app/rawak/page.tsx
- components/ui/institution-card.tsx
Improve rawak page on both web and mobile layout. More on commit details
> Improve rawak page

- app/page.tsx
- app/rawak/page.tsx
- components/custom-map.tsx
- components/filter-category.tsx
- components/filtered-count.tsx
https://github.com/user-attachments/assets/9a175dbc-a3bc-4a8d-a23a-45897b07d8b6
> Update count UI

- app/[institution]/[slug]/page.tsx
- app/page.tsx
- components/custom-map.tsx
- components/map.tsx
**Changes**
- Expand map to full width when toggled
- Add animation
- Externalize toggle state (separate button)
**Before:**
https://github.com/user-attachments/assets/213cc01d-bce6-45b0-b1d6-50cb9c80037c
**After**
https://github.com/user-attachments/assets/d2d64377-00b7-4317-a863-61085d937f60
> Optimize map component, maximize display, animation

- app/page.tsx
- components/custom-map.tsx
- components/map.tsx
https://github.com/user-attachments/assets/e256e563-1607-42d6-9b13-9454db5068f0
> Apply state and category filters to map

- app/data/institutions.ts
Related to #183 
Added until this mosque: https://www.facebook.com/photo/?fbid=10231252107501958&set=pcb.10231238536122682
Data is skipped when already in sedekahje, or not enough information found eg unreadable QR, place not found etc,.
> feat: Add surau & mosques QR

- README.md
- code for QR bulk contribution
- run on notebook, no local setup 
- see [notebook](https://colab.research.google.com/drive/1ObRdwFqF9Ug6f1UjvDPB0X7m3hAyMaQj?usp=sharing)
> readme: added code for bulk qr contribution 

- .github/ISSUE_TEMPLATE/add_qr_code.md
- .github/workflows/add_qrcode.yml
- README.md
- actions/append_institution.js
- actions/extractFields.js
> .github/ISSUE_TEMPLATE/add_qr_code.md
> - issue template for adding new qr code
> 
> .github/workflows/add_qrcode.yml
> - github actions workflow for creating PR based on issue
> 
> actions/append_institution.js
> - code for adding new qrcode into intitutions.ts
> 
> actions/extractFields.js
> - code for extracting value from issue form
Already 5 years not touch javascript and github actions, let me know if the code weird or outdated
---
How to use:
1. create new issue
2. pick 'Add New QR Code' template
3. Replace placeholder
4. submit
> Create PR from issues

- .github/ISSUE_TEMPLATE/add_qr_code.md
- actions/append_institution.js
This PR for adding new field remarks for issue and use that data for institutions.ts comment
> add field remarks

- .github/workflows/add_qrcode.yml
Reverts khrnchn/sedekah-je#242
> Revert ":8ball: update workflow (thanks claude)"

- .github/workflows/add_qrcode.yml
- actions/append_institution.js
- actions/extractFields.js
link contributor from issue
~~use id based on issue and plus 1000~~
~~PENDING: separate PR for auto resolving conflict~~
Need to restructure the data, appending will always trigger conflict https://github.com/khrnchn/sedekah-je/pull/255#issuecomment-2466498666
> add contributor properly

- app/data/institutions.ts
#183 
- added 5 new institutions
- scanned the QRs and the bank's name matched
- others are just cosmetics (removed new lines)
> From Facebook link

- app/data/institutions.ts
> Add Masjid As-Salam PJ

- app/(dashboard)/dashboard/_components/stats.tsx
- app/(dashboard)/dashboard/_lib/actions.ts
- components/app-sidebar.tsx
- components/nav-main.tsx
- **feat: 🎸 add total institutions badge in sidebar and stats query**
- **fix: 🐛 stats count query**
- **fix: 🐛 stats query**
> :hammer: update stats query

- app/(user)/_components/client-layout.tsx
- app/(user)/_components/nav.tsx
- app/(user)/layout.tsx
- components/rawak-footer.tsx
- components/ui/header.tsx
- components/ui/user-nav.tsx
- update layout session checking -> server side
> 👍🏽 feat: nak tambah qr button to check user session before redirect
